json.id user.id
json.first_name user.first_name
json.last_name user.last_name
json.full_name user.full_name
json.role user.role
json.email user.email
json.prepper user.prepper
json.organist user.organist
json.chorister user.chorister
json.conductor user.conductor