default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sacrament_meeting_planner_development

test:
  <<: *default
  database: sacrament_meeting_planner_test

production:
  <<: *default
  host: <%=ENV.fetch('DB_HOST', 'localhost') %>
  database: <%=ENV.fetch('DB_NAME', 'sacrament-meeting-planner-production') %>
  username: <%=ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
